class: de.unihamburg.sickstore.database.SickServer
port: 54000
queryHandler:
    class: de.unihamburg.sickstore.backend.QueryHandler
    anomalyGenerator:
        class: de.unihamburg.sickstore.backend.anomaly.BasicAnomalyGenerator
#        stalenessGenerator:
#            class: de.unihamburg.sickstore.backend.anomaly.staleness.ConstantStaleness
#            foreignReads: 500
#            ownReads: 0
#        clientDelayGenerator:
#            class: de.unihamburg.sickstore.backend.anomaly.MongoDbAnomalies
        combinedGenerator:
            class: de.unihamburg.sickstore.backend.anomaly.MongoDbAnomalies
            defaultDelay: 1
            journalCommitInterval: 1
            customDelays:
                # to, from, delay
                - [primary, secondary1, 1]
                - [primary, secondary2, 5]
                - [secondary1, primary, 1]
                - [secondary2, primary, 5]
            tagSets:
                foobar:
                    A: 1
                    B: 2
    nodes:
        -
            class: de.unihamburg.sickstore.database.Node
            name: primary
            primary: true
            clientLatency: 2
            throughput:
                max: 200.0
                hickupEvery: 10000
                hickupDuration: 200
            tags:
                - A
                - B
        -
            class: de.unihamburg.sickstore.database.Node
            name: secondary1
            clientLatency: 2
            maxThroughput: 100.0
            tags:
                - A
        -
            class: de.unihamburg.sickstore.database.Node
            name: secondary2
            clientLatency: 2
            maxThroughput: 100.0
            tags:
                - B