class: de.unihamburg.sickstore.database.SickServer
port: 54000
queryHandler:
    class: de.unihamburg.sickstore.backend.QueryHandler
    anomalyGenerator:
        class: de.unihamburg.sickstore.backend.anomaly.BasicAnomalyGenerator
        combinedGenerator:
            class: de.unihamburg.sickstore.backend.anomaly.MongoDbAnomalies
            defaultDelay: 0
            tagSets:
                foobar:
                    A: 1
    nodes:
        -
            class: de.unihamburg.sickstore.database.Node
            name: primary
            primary: true
            tags:
                - A
        -
            class: de.unihamburg.sickstore.database.Node
            name: secondary1
            tags:
                - A
        -
            class: de.unihamburg.sickstore.database.Node
            name: secondary2
            tags:
                - A